### PR TITLE
Additions to Parser

### PR DESCRIPTION
**Pull request by marauder1**
Added functions for whip and flashlight.

### CODE REVIEW

**Comment by michaeldton** [comment]
adding files via upload/copy+paste might be causing the conflicts, or is at least making it difficult to see what it is b/c it might be recognizing the file you are uploading as completely different and marking every line as a conflict. can you try re-doing it, and pushing it to the feature-text-parser branch instead of main?

**Comment by michaeldton** [comment]
could also be that the original file needs to be linted to match PEP8 - will check that in the AM

**Comment by marauder1** [comment]
Ok, I'll try in the morning. Cheers!

**Comment by michaeldton** [comment]
cool! feel free to ping me in Slack if you get stuck on something

**Pull request closed without merging**
